export { default as Header } from "./Header";
export { default as Menu } from "./Menu";
export { default as Footer } from "./Footer";
export { default as Layout } from "./Layout";
// export { default as Loader } from "./Loader";
export { default as Social } from "./Social";
export { default as Side } from "./Side";
export { default as Email } from "./Email";
export { default as Hero } from "./sections/Hero";
export { default as About } from "./sections/About";
// export { default as Jobs } from "./sections/Jobs";
// export { default as Projects } from "./sections/Projects";
// export { default as Contact } from "./sections/Contact";